### PR TITLE
Upgrade to scala 2.13 + drop scala 2.11 support

### PR DESCRIPTION
**Pull request by lorandszakacs**
Had to set docs to use only `2.12` ~and `2.11`~ because of github4s. But I guess it's ok that docs don't compile on `2.13` yet, right? 😅 

Disclaimer: scalafmt did the whole thing in the http4s modules, not me 😇. I just had to fully qualify the name to the `parser` since it no longer compiled as it was.

Later updates:
Since http4s dropped scala `2.11` support since `0.21.0-M2` decided to drop it in this PR as well. I guess all other modules can technically be published for `2.11` as well and have only the http4s one be published only for `2.12` and `2.13`. Let me know what the desired approach is, I can update this PR w/ either.

### CODE REVIEW

**Comment by ChristopherDavenport** [comment]
We can get 1 out so an artifact exists, but really this should be behind cats-effect/fs2/http4s release based on the cats RC as well.

**Comment by lorandszakacs** [comment]
Both builds failed w/ `Server access Error: Connection timed out (Connection timed out) url=https://repo.scala-sbt.org/scalasbt/maven-releases/...` 😅 
how can we trigger a manual rebuild? Since it simply seems that downloading new dependencies was taking too long.

**Comment by ChristopherDavenport** [comment]
Options available from the outside are closing and reopening a PR.

Repo Administrators can restart builds. I have just done so.

**Comment by lorandszakacs** [comment]
Something goes on with the build that I have never encountered before. Why do modules try to resolve the dependencies from an external repo instead of them being source dependencies? 😅 
If I compile and test each module independently (how I actually did it locally) it works 😕did not expect for the global task to fail...

**Comment by lorandszakacs** [comment]
So, after doing the necessary SBT incantations, I managed to get `+docs/compile` to work on a clean build, but not also `docs/compile` 😄

But then I realized that if I put the default scala version to `2.12.x` `docs/compile` also works 😄. Kinda makes sense. Hopefully build should work now w/ latest commit.

**Comment by lorandszakacs** [comment]
Ok, was hoping that this wouldn't be necessary, but I can't find any other solution. Previous attempt did not work because travis doesn't build with `+test` but w/ `++$SCALA_VERSION test`, two very different things 😭.

Now, the end result should be that travis will correctly build everything, but in a rather hacky way.
- [x] excluded `docs` from root aggregate,  because the command `sbt ++2.13.0 test` (used by travis) also propagates to `docs`, while `+test` doesn't...
- [x] travis explicitly builds docs using `2.12.9`

**Comment by lorandszakacs** [comment]
The build that keeps on giving, sorry for the long list of comebacks...

Docs now works properly, but mima fails when it tries to compare to  `0.2.0_2.13` versions even though `mimaFailOnNoPrevious := false`. I am currently at a loss on how to fix this, might take some time to figure out 😭

**Comment by lorandszakacs** [comment]
Ok, finally managed to get it to work. With hacks being applied only to `docs` build 😅 . And without bumping the version to `0.3.0-SNAPSHOT` to cheat mima. Although this might be desirable given that fs2 and http4s did minor version increases.

Reverted to scala `2.12.8` instead of `2.12.9` because it brought in non-binary compatible changes in the `core`, `fs2`, and `http4s` modules. My mima foo is not good enough to tackle these yet though.

Unfortunately I have only ~12 hours left until I have to leave for my vacation without any laptop, so I won't be able able to work on this too much more 😅.

@ChristopherDavenport please take another look at the build and whatnot, since I changed more things than I would have liked, and you might not approve of these changes.

**Comment by ChristopherDavenport** [comment]
Increase the version, otherwise looks good.

**Pull request merged**
